version: '3.8'

services:
      
  db_postgres:
    image: postgres:12.7
    container_name: ps_12_7
    restart: always

    volumes:
     - ./db_psql12/create_dbt_psql.sh:/docker-entrypoint-initdb.d/create_dbt_psql.sh
#     - ./db_psql12/pgdata:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: crypto_db

    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-cont:
    build: ./add_data
    container_name: pycont
    volumes:
      - ./add_data:/app
    depends_on:
      db_postgres:
        condition: service_healthy
 #   command: echo "python - cont started"
 # si le clavas el command de arriba, te pisa el CMD del Dockerfile y nunca corre el script

  python-query:
    build: ./query_data
    container_name: pyquery
    volumes:
      - ./query_data:/app_query
    depends_on:
      db_postgres:
        condition: service_healthy
      python-cont:
        condition: service_completed_successfully
    #command: tail -f /dev/null




    


